[package]
name = "json-cli"
version = "0.1.0"
edition = "2021"
description = "Helpers for creating CLIs with serializable JSON output."

[dependencies]
anyhow = "1.0.42"
async-trait = "0.1.56"
clap = { version = "3.2", features = ["derive"] }
serde = { version = "1.0.137" }
serde_json = "1.0.81"
